### ISSUE TITLE
App crashes Unhandled Exception: ServicesBinding.defaultBinaryMessenger

### ISSUE THREAD

**Issue by javier-elizaga** [anwar907/flutter-clock#2]
I tried to run your clock to see what you did with flare and its not working. 
You'll need to add `WidgetsFlutterBinding.ensureInitialized();` statement in your main.dart. Before the deadline.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  ...
```

**Comment by anwar907** [comment]
> I tried to run your clock to see what you did with flare and its not working.
> You'll need to add `WidgetsFlutterBinding.ensureInitialized();` statement in your main.dart. Before the deadline.
> 
> ```
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   ...
> ```

thank you, I will fix it
